---
# roles/multimedia/tasks/main.yml

- name: installing multimedia packages
  sudo: yes
  apt: name={{ item }} state=latest
  when: ansible_os_family == "Debian"
  with_items:
    - vlc
    - asunder
    - easytag
