---
# a playbook to apply on self (i.e update your workstation)
# it should be used with a stub inventory
- hosts: all
  # connection: local
  # one must sudo su to run as root on localhost from non-root
  remote_user: root
  sudo: yes

  # use an external var file like so to load variables:
  vars_files:
  - assets/users/defaults.yml
  # - "{{ playbook_dir }}/assets/users/defaults.yml"

  roles:
  - accounts
  - common
  # - ansiblecm
  # - collectd
  # - docker
  # - network
  # - fail2ban

  tasks:
    - include: task_lib/virtualbox_vl.yml
  # roles:
  #   - common
  #   - dotfiles
  #   - workstation
