---

  # one must sudo su to run as root on localhost from non-root that is why we
  # need sudo
- hosts: workstations
  remote_user: root
  become: yes
  # vars_files:
  #   - "{{ playbook_dir }}/assets/account_profiling/default.yml"
  # roles:
  #   - { role: accounts, accounts_profile: vl_account.yml }
      # - accounts
    # - { role: accounts, useraccountfiles: [ default.yml ]}

  vars_files:
  - "{{ playbook_dir }}/{{ private_dir }}/users/users.yml"

  roles:
    - accounts

- hosts: workstations
  remote_user: archf
  become: yes

  roles:
  - common
  - synergy
  - workstation
  - docker

  # - network
    # - dotfiles
  tasks:
    - include: task_lib/virtualbox_vl.yml
