---

# load users vars wich contains a list pointing to the user dotfiles repo
- include: "{{ playbook_dir }}/task_lib/load_users_vars.yml"

- name: Ensure git (client) is properly installed on RedHat os family systems
  sudo: yes
  yum: name=git state=present
  when: ansible_os_family == "RedHat"

- name: Ensure git (client) is properly installed on Debian os family systems
  sudo: yes
  apt: name=git state=present
  when: ansible_os_family == "Debian"

- name: check if dotfiles repo has already been cloned
  remote_user: "{{ item.name }}"
  command: if [ -d "~/dotfiles" ]; then echo "true"; else echo "false"; fi
  register: dotfiles_exists
  with_items: users

- name: pull dotfile repo over https
  remote_user: "{{ item.name }}"
  debug: dest="{{ item.home  | default('/home/' + item.name ) ~ '/dotfiles' }}"
  with_items: users

# - name: pull dotfile repo over https
#   remote_user: "{{ item.name }}"
#   git: repo=https://archambf@bitbucket.org/archambf/dotfiles.git
#        dest="{{ item.home | default('/home/' + item.name ) ~ '/dotfiles' }}"
#   with_items: users
#   when: not dotfiles_exists


