---

# install openssh-server and configure sshd_config on each node

- name: install openssh-server and openssh-client
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: packages

- name: template sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes
