---

# NOTE: only work on rhel derivatives for now

- name: load OS specific variables (see roles/*/vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: ensure network packages are installed
  sudo: yes
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: packages

  # not os specific
- name: template the interface configuration file
  sudo: yes
  template: src=ether_{{ ansible_os_family }}.j2 dest={{ netwrk_conf_path }}/ifcfg-{{ item.device }} mode=0622
  with_items: ifaces
  when: ifaces is defined
  register: changed_ifaces

  # os specific
- name: template the route configuration configuration file
  sudo: yes
  template: src=route_{{ ansible_os_family }}.j2 dest={{ netwrk_conf_path }}/route-{{ item.device }} mode=0622
  with_items: ifaces
  when: ifaces is defined and item.routes is defined and ansible_os_family == 'RedHat'

# - name: restart changed interfaces
#   sudo: yes
#   shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
#   with_items: changed_ifaces.results
#   when: changed_ifaces is defined and item.changed
