---
# file: roles/common/tasks/main.yml
- name: test connection
  ping:
  # remote_user: vagrant

- name: installing default packages on any machine
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - tmux
    - gvim
    - vim
    - python3
    - htop
    - git
    - fakeroot
    - tree
    - wireshark
    - openssh-server
    - gdisk
    - rsync
    - lvm2
    - libncurses5-dev
    - libncurses5
  when: ansible_os_family == "Debian"
