---
# list of packages to install by default on any debian family system
packages:
  - tmux
  - mosh
  - git
  - vim-gtk
  - vim
  - python3
  - htop
  - git
  - fakeroot
  - tree
  - openssh-server
  - gdisk
  - rsync
  - lvm2
  - libncurses5-dev
  - libncurses5
  - nmap
  - fail2ban
  - gcc
  - linux-kernel-headers
  - zsh
  - sshpash
