---
packager: yum
packages:
  - tmux
  - mosh
  - sudo
  - git
  - python3
  - htop
  - git
  - tree
  - openssh-server
  - gdisk
  - rsync
  - lvm2
  - ncurses-devel
  - ncurses
  - nmap
  - fail2ban
  - gcc
  - kernel-devel
  - vim-common
  - vim-X11
  - zsh
